export const SCREENS = {
  ActorWE: "ActorScreen",
  AlbumInput: "AlbumInput",
  AuthNav: "AuthNav",
  ActorEdu: "ActorEducation",
  CreatePassword: "CreatePassword",
  CelebBio: "inputForm",
  CricketStatistics: "CricketStatisticsScreen",
  Category: "CategoryScreen",
  FootBallStatistics: "FootballStatisticsScreen",
  Gallery: "Gallery",
  LogIn: "LoginScreen",
  NamingApp: "NamingAppScreen",
  SPLASH: "Splash",
  SingerWE: "SingerWE",
  SingerCD: "SingerCD",
  SignUp: "SignUpScreen",
  SearchAccount: "SearchAccountScreen",
  SportsInfo: "SportsInfoScreen",
  SportsAchievements: "SportsAchievementsScreen",
  SocialAccounts: "SocialAccounts",
<<<<<<< HEAD
  PoliticianInfo: "PoliticianInfo",
  PoliticianAchievement: "politicianAchievement",
  PoliticianEducation: "politicianEducation",
  PoliticianProjects: "politicianProjects",
=======
  GenerateApk: "GenerateApk",
>>>>>>> 2c85380319dfa00595c08384e554727f48f005df
};
