export const SCREENS = {
  SPLASH: "Splash",
  ActorWE: "ActorScreen",
  CelebBio: "inputForm",
  SingerWE: "SingerWE",
  AlbumInput: "AlbumInput",
  SingerCD: "SingerCD",
  LogIn: "LoginScreen",
  SignUp: "SignUpScreen",
  SearchAccount: "SearchAccountScreen",
  NamingApp: "NamingAppScreen",
  Category: "CategoryScreen",
  SportsInfo: "SportsInfoScreen",
  SportsAchievements: "SportsAchievementsScreen",
  Statistics: "StatisticsScreen",
  AuthNav: "AuthNav",
  Gallery: "Gallery",
  SocialAccounts: "SocialAccounts",
  ActorEdu: "ActorEducation",
};
